global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using MeowFlix.Common;
global using MeowFlix.Models;
global using MeowFlix.ViewModels;
global using MeowFlix.Views;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Data;
global using Microsoft.UI.Xaml.Navigation;
global using System.Collections.ObjectModel;
global using WinUICommunity;
global using static MeowFlix.Common.AppHelper;
global using static MeowFlix.Common.LoggerSetup;
